# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Chat' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'LeanCloud', '~> 17.0.0-beta.3'
  pod 'AlamofireImage', '~> 4.0.0-beta.5'
  pod 'AgoraRtcEngine_iOS', '~> 2.9'
end
