# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Chat' do
  use_frameworks!
  inhibit_all_warnings!

#  pod 'LeanCloud', '~> 16.0.0-beta.8'
  pod 'LeanCloud', :path => '../../swift-sdk'
end
